### ISSUE TITLE
Unable to import pyromocc

### ISSUE THREAD

**Issue by steveroeder** [SINTEFMedtek/libromocc#7]
I am not able to import pyromocc into python code.  I get the error below:

```steve@steve:~/Desktop/robot$ python
Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyromocc import Robot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/steve/Desktop/robot/venv/lib/python3.11/site-packages/pyromocc/__init__.py", line 2, in <module>
    from .pyromocc import *
ModuleNotFoundError: No module named 'pyromocc.pyromocc'
```

**Comment by androst** [comment]
Hi,
Could you check if the artifact uploaded with the latest build solves your problem? 
Unzip Python wheel and run pip install on the wheel file (pyromocc-0.0.6-cp311-cp311-manylinux_2_31_x86_64.linux_x86_64.whl).

**Comment by androst** [comment]
Confirmed that this works with new wheels.
